/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [

    {
      type: "autogenerated",
      dirName: ".", // '.' means the current docs folder
    },
    // {
    //   type: 'category',
    //   label: 'Arbitrum-v3',
    //   collapsible: true,
    //   collapsed: false,
    //   items: ['Arbitrum-v3/enums'],
    // },
    
    // {
    //   type: 'link',
    //   label: 'Github', // The link label
    //   href: 'https://github.com/justmert/aave-graphql-doc', // The internal path
    // },

  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
